"use strict";

const PUBLIC_API_URL = "https://script.google.com/macros/s/AKfycbxI4Ipy5_29hvX05kEhbPb4d8GEc-G3BP7V0POXdjL5Z37Oq6TcSNKqw_OvHwSWfQjjqw/exec";
const map = L.map("map", {zoomControl:false, preferCanvas:true, zoomSnap:.25}).setView([43.1117,-79.0396],13);
L.control.zoom({position:"bottomright"}).addTo(map);
const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);
const satellite=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxNativeZoom:19,maxZoom:21,attribution:"Esri World Imagery"});
L.control.layers({Streets:street,Satellite:satellite},{},{position:"topright"}).addTo(map);

const surveyLayers=new Map();
let published=[];
let searchMarker=null;
const els={
  search:document.getElementById("locationSearch"),searchBtn:document.getElementById("locationSearchBtn"),searchStatus:document.getElementById("searchStatus"),
  refreshBtn:document.getElementById("refreshBtn"),libraryStatus:document.getElementById("libraryStatus"),surveyList:document.getElementById("surveyList"),
  legendBtn:document.getElementById("legendBtn"),legendPanel:document.getElementById("legendPanel"),legendClose:document.getElementById("legendClose")
};
els.searchBtn.addEventListener("click",searchLocation);els.search.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();searchLocation();}});els.refreshBtn.addEventListener("click",loadPublished);
els.legendBtn.addEventListener("click",()=>setLegend(els.legendPanel.hidden));els.legendClose.addEventListener("click",()=>setLegend(false));
function setLegend(open){els.legendPanel.hidden=!open;els.legendBtn.setAttribute("aria-expanded",String(open));}

async function api(action,payload={}){
  const response=await fetch(PUBLIC_API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})});
  const result=await response.json();if(!result.ok)throw new Error(result.error||"Request failed");return result;
}

function parseCoordinates(value){const m=value.trim().match(/^\s*([+-]?\d+(?:\.\d+)?)\s*[, ]\s*([+-]?\d+(?:\.\d+)?)\s*$/);if(!m)return null;const lat=Number(m[1]),lng=Number(m[2]);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180?{lat,lng}:null;}
function placeSearchMarker(lat,lng,label){if(searchMarker)map.removeLayer(searchMarker);searchMarker=L.marker([lat,lng]).addTo(map).bindPopup(label);map.setView([lat,lng],Math.max(map.getZoom(),18));searchMarker.openPopup();}
async function searchLocation(){const q=els.search.value.trim();if(!q){els.searchStatus.textContent="Enter an address or latitude, longitude.";return;}const c=parseCoordinates(q);if(c){placeSearchMarker(c.lat,c.lng,`${c.lat.toFixed(6)}, ${c.lng.toFixed(6)}`);els.searchStatus.textContent=`Centered on ${c.lat.toFixed(6)}, ${c.lng.toFixed(6)}.`;return;}els.searchBtn.disabled=true;els.searchStatus.textContent="Searching address…";try{const url=new URL("https://nominatim.openstreetmap.org/search");url.searchParams.set("q",q);url.searchParams.set("format","jsonv2");url.searchParams.set("limit","1");const r=await fetch(url,{headers:{Accept:"application/json"}});const rows=await r.json();if(!rows.length){els.searchStatus.textContent="No address match found.";return;}placeSearchMarker(Number(rows[0].lat),Number(rows[0].lon),rows[0].display_name);els.searchStatus.textContent=rows[0].display_name;}catch{els.searchStatus.textContent="Address search could not connect. Coordinates still work.";}finally{els.searchBtn.disabled=false;}}

async function loadPublished(){els.libraryStatus.textContent="Loading published surveys…";els.surveyList.innerHTML="";for(const layer of surveyLayers.values())map.removeLayer(layer);surveyLayers.clear();try{const result=await api("publicList");published=result.surveys||[];renderLibrary();els.libraryStatus.textContent=published.length?`${published.length} published survey${published.length===1?"":"s"}.`:"No surveys have been published yet.";}catch(e){els.libraryStatus.innerHTML=`<span class="loading-error">${escapeHtml(e.message)}</span>`;}}
function renderLibrary(){els.surveyList.innerHTML="";published.forEach(row=>{const item=document.createElement("article");item.className="public-survey-item";item.innerHTML=`<div class="public-survey-top"><label class="survey-toggle"><input type="checkbox" data-survey="${escapeHtml(row.id)}"><span><h3>${escapeHtml(row.name||"Untitled survey")}</h3><span class="public-survey-meta">${escapeHtml(cap(row.type||"other"))} · ${escapeHtml(formatDate(row.date))}<br>${escapeHtml(row.observer||"Observer not listed")} · ${escapeHtml(row.detectorModel||"Detector not listed")}<br>${escapeHtml(row.location||"Location not listed")}</span></span></label><span class="status-pill">Published</span></div>`;const box=item.querySelector("input");box.addEventListener("change",()=>toggleSurvey(row,box.checked,box));els.surveyList.appendChild(item);});}
async function toggleSurvey(row,show,box){if(!show){const layer=surveyLayers.get(row.id);if(layer)map.removeLayer(layer);return;}box.disabled=true;try{let layer=surveyLayers.get(row.id);if(!layer){const result=await api("publicData",{id:row.id});const points=parseSurvey(result.fileName,result.text);layer=buildSurveyLayer(row,points);surveyLayers.set(row.id,layer);}layer.addTo(map);if(layer.getBounds&&layer.getBounds().isValid())map.fitBounds(layer.getBounds(),{padding:[35,35]});}catch(e){box.checked=false;alert(`Could not load ${row.name}: ${e.message}`);}finally{box.disabled=false;}}
function buildSurveyLayer(row,points){const group=L.featureGroup();const values=points.map(metricValue).filter(Number.isFinite);const min=values.length?Math.min(...values):0,max=values.length?Math.max(...values):1;const latlngs=points.map(p=>[p.lat,p.lng]);if(latlngs.length>1&&row.type!=="stationary")L.polyline(latlngs,{color:"#4d0f14",weight:3,opacity:.65,dashArray:row.type==="drone"?"8 5":null}).addTo(group).bindPopup(summaryHtml(row));points.forEach(p=>{const v=metricValue(p),t=max>min?(v-min)/(max-min):.35;const radius=row.type==="stationary"?7:4;L.circleMarker([p.lat,p.lng],{radius,weight:1,color:"#fff",fillColor:scaleColor(t),fillOpacity:.9}).addTo(group).bindPopup(pointHtml(row,p));});return group;}
function metricValue(p){for(const v of [p.cpm,p.cps,p.doseRate])if(Number.isFinite(v))return v;return NaN;}
function scaleColor(t){if(t<.25)return"#d9c8aa";if(t<.5)return"#b88961";if(t<.75)return"#6f161c";return"#26070a";}
function summaryHtml(r){return `<div class="survey-tooltip"><strong>${escapeHtml(r.name)}</strong><br>${escapeHtml(cap(r.type))} · ${escapeHtml(formatDate(r.date))}<br>${escapeHtml(r.observer||"")}<br>${escapeHtml(r.detectorModel||"")}${r.detectorHeight?` · ${escapeHtml(r.detectorHeight)}`:""}${r.notes?`<br><br>${escapeHtml(r.notes)}`:""}</div>`;}
function pointHtml(r,p){const vals=[];if(Number.isFinite(p.cpm))vals.push(`${p.cpm} CPM`);if(Number.isFinite(p.cps))vals.push(`${p.cps} CPS`);if(Number.isFinite(p.doseRate))vals.push(`${p.doseRate} µSv/h`);return `<div class="survey-tooltip"><strong>${escapeHtml(r.name)}</strong><br>${vals.length?vals.join(" · "):"Measurement point"}${p.timestamp?`<br>${escapeHtml(p.timestamp)}`:""}<br>${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}</div>`;}

function parseSurvey(name,text){const lower=String(name||"").toLowerCase();if(lower.endsWith(".geojson")||lower.endsWith(".json"))return parseGeo(JSON.parse(text));if(lower.endsWith(".gpx"))return parseGpx(text);return parseCsv(text);}
function norm(v){return String(v||"").trim().toLowerCase().replace(/[\s_.-]+/g,"");}
function parseCsvRows(text){const out=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(c===","&&!q){row.push(cell);cell="";}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);cell="";if(row.some(x=>String(x).trim()))out.push(row);row=[];}else cell+=c;}row.push(cell);if(row.some(x=>String(x).trim()))out.push(row);return out;}
function idx(headers,names){const hs=headers.map(norm);return hs.findIndex(h=>names.includes(h));}
function parseCsv(text){const rows=parseCsvRows(text);if(rows.length<2)throw new Error("No data rows.");const h=rows[0],la=idx(h,["lat","latitude","gpslatitude"]),lo=idx(h,["lon","lng","long","longitude","gpslongitude"]);if(la<0||lo<0)throw new Error("CSV needs latitude and longitude columns.");const ci=idx(h,["cpm","countsperminute","countratecpm"]),si=idx(h,["cps","countspersecond","countratecps"]),di=idx(h,["dose","doserate","usvh","µsvh","microsieverthour"]),ti=idx(h,["timestamp","datetime","dateandtime","time"]);const pts=[];rows.slice(1).forEach(r=>{const lat=Number(r[la]),lng=Number(r[lo]);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;pts.push({lat,lng,cpm:ci>=0?num(r[ci]):null,cps:si>=0?num(r[si]):null,doseRate:di>=0?num(r[di]):null,timestamp:ti>=0?r[ti]:null});});if(!pts.length)throw new Error("No valid coordinates.");return pts;}
function parseGeo(input){const pts=[];function add(c,p={}){if(!Array.isArray(c)||c.length<2)return;const lng=Number(c[0]),lat=Number(c[1]);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;pts.push({lat,lng,cpm:num(p.cpm??p.CPM),cps:num(p.cps??p.CPS),doseRate:num(p.dose_rate??p.doseRate??p.usvh),timestamp:p.timestamp??p.time??null});}function walk(f){if(!f)return;if(f.type==="FeatureCollection")return f.features.forEach(walk);if(f.type==="Feature"){const g=f.geometry||{},p=f.properties||{};if(g.type==="Point")add(g.coordinates,p);else if(g.type==="LineString")g.coordinates.forEach(c=>add(c,p));else if(g.type==="MultiLineString")g.coordinates.flat().forEach(c=>add(c,p));}}walk(input);if(!pts.length)throw new Error("No point or line coordinates in GeoJSON.");return pts;}
function parseGpx(text){const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.querySelector("parsererror"))throw new Error("Invalid GPX.");const pts=[];doc.querySelectorAll("trkpt,wpt,rtept").forEach(n=>{const lat=Number(n.getAttribute("lat")),lng=Number(n.getAttribute("lon"));if(Number.isFinite(lat)&&Number.isFinite(lng))pts.push({lat,lng,cpm:num(findText(n,["cpm"])),cps:num(findText(n,["cps"])),doseRate:num(findText(n,["doserate","usvh","dose"])),timestamp:findText(n,["time"])});});if(!pts.length)throw new Error("No GPX points.");return pts;}
function findText(node,names){for(const name of names){const direct=node.querySelector(name);if(direct)return direct.textContent;for(const el of node.querySelectorAll("*")){if(norm(el.localName)===norm(name))return el.textContent;}}return null;}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function cap(s){return String(s||"").replace(/^./,c=>c.toUpperCase());}function formatDate(v){const s=String(v||"");const m=s.match(/\d{4}-\d{2}-\d{2}/);return m?m[0]:s||"No date";}function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
loadPublished();
